apiVersion: v1
kind: Service
metadata:
  name: tech-portfolio-service
spec:
  selector:
    app: tech-portfolio
  ports:
    - protocol: TCP
      port: 80 # Service 监听的端口 (外部访问端口)
      targetPort: 80 # Pod 监听的端口 (容器内部 Nginx 端口)
  type: LoadBalancer # 这会在 Azure 中创建一个公共 IP 地址的负载均衡器